services:
  thingsboard:
    image: thingsboard/tb-postgres
    ports:
      - "8080:9090"
    env_file:
      - .env
    environment:
      TB_QUEUE_TYPE: in-memory
      TB_DB_TYPE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://your_neon_host/dbname
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 