services:
  mytb:
    image: thingsboard/tb-postgres
    restart: always
    ports:
      - "8080:9090"         # Web UI
      - "1883:1883"         # MQTT
      - "7070:7070"         # HTTP
      - "5683-5688:5683-5688/udp"  # CoAP
    environment:
      TB_QUEUE_TYPE: in-memory
      TB_DB_TYPE: postgres
      TB_DB_HOST: ep-your-neon-host.ap-southeast-1.aws.neon.tech
      TB_DB_PORT: 5432
      TB_DB_NAME: neondb
      TB_DB_USERNAME: neondb_owner
      TB_DB_PASSWORD: your_neon_password
      TB_SSL_ENABLED: "true"              # ADD THIS for Neon (requires SSL)
      TB_SCHEDULER_ENABLED: "false"       # Optional
    volumes:
      - mytb-logs:/var/log/thingsboard

volumes:
  mytb-logs:
